# Generated by Django 5.2.9 on 2025-12-26 08:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tên sách")),
                (
                    "asin",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="ASIN",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WRITING", "Đang viết"),
                            ("DESIGN", "Đang thiết kế"),
                            ("LIVE", "Đang bán"),
                        ],
                        default="WRITING",
                        max_length=20,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Doanh thu Royalty (VND)",
                    ),
                ),
                (
                    "cost_production",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Chi phí SX (VND)",
                    ),
                ),
                (
                    "cost_ads",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=15,
                        verbose_name="Chi phí Ads (VND)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.IntegerField(default=40000)),
            ],
        ),
        migrations.CreateModel(
            name="TaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Tên công việc"),
                ),
                (
                    "standard_hours",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Định mức giờ"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Đã xong"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Đã trả lương"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người làm",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.book"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.tasktemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Số giờ làm"
                    ),
                ),
                ("note", models.TextField(verbose_name="Mô tả CV")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Duyệt"),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Số tiền (VND)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("REVENUE", "Doanh thu"),
                            ("COST_PRODUCTION", "Chi phí SX"),
                            ("COST_ADS", "Chi phí Ads"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.book",
                    ),
                ),
            ],
        ),
    ]
